# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.author.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ottmar's Notes
description: Ottmar's public notes on coding - mainly about Oracle APEX and PL/SQL
author:
  name: Ottmar Gobrecht
  url: https://github.com/ogobrecht
  email: ottmar.gobrecht@gmail.com
  github: ogobrecht
  twitter: ogobrecht
  xing: Ottmar_Gobrecht
url: "https://ogobrecht.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /posts/:year-:month-:day-:title
lang: en # the base language of your site, can be overwritten on a page or post
feed_limit: 20

disqus:
  shortname:
google_analytics:

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "slides"
    values:
      layout: "slides"
  -
    scope:
      path: "tags"
    values:
      layout: "tag"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
